build_path: 
  win32: C:\Users\Fisher\Documents\Unity\build-obstacle-roller\rl-test.exe
  linux: /data/linux-obstacle-roller/rl-test.x86_64
write_summary_graph: true
seed_increment: 100
max_iter: 10000
decay_steps: 200
decay_rate: 0.9
addition_objective: true
epsilon: 0.05
init_td_threshold: 0.2
td_threshold_decay_steps: 300