build_path: 
  win32: C:\Users\Fisher\Documents\Unity\build-simple-boat\boat.exe
  linux: /data/linux-test-boat/boat.x86_64
write_summary_graph: true
seed_increment: 100

init_td_threshold: 0.1

min_lr: 0.0
decay_steps: 400
decay_rate: 0.8

max_iter: 10000
lambda: 0.99