build_path: 
  win32: C:\Users\Fisher\Documents\Unity\build-simple-boat\RL-Envs.exe
  linux: /data/zzy/linux-simple-boat/RL-Envs.exe
write_summary_graph: true
seed_increment: 100

decay_rate: 1

max_iter: 10000
lambda: 0.99

beta: 0.002

addition_objective: true
epsilon: 0.05