build_path: 
  win32: C:\Users\Fisher\Documents\Unity\build-3dball-500step\rl-test.exe
  linux: /data/build-linux-3dball-500step/rl-test.x86_64
write_summary_graph: true
seed_increment: 200
decay_steps: 50
decay_rate: 0.7
addition_objective: true
epsilon: 0.02