build_path: 
  win32: C:\Users\Fisher\Documents\Unity\build-3dball-hard\rl-test.exe
  linux: /data/linux-3dball-hard/rl-test.x86_64
write_summary_graph: true
max_iter: 5000
seed_increment: 200
decay_steps: 100
decay_rate: 0.8
addition_objective: true
epsilon: 0.02