build_path: 
  win32: C:\Users\Fisher\Documents\Unity\build-RL-Envs\RL-Envs.exe
scene: 3DBall

# lambda: 1
# gamma: 0.99
max_iter: 5000
# policies_num: 1
# agents_num_p_policy: 1
# reset_on_iteration: true
seed: 100
# std: true
# mix: true
# aux_cumulative_ratio: 0.4
# good_trans_ratio: 1
addition_objective: true

ppo_config:
  # save_per_iter: 1000
  write_summary_graph: true

  # batch_size: 2048
  # epoch_size: 10

  # init_td_threshold: 0.0
  # td_threshold_decay_steps: 100
  # td_threshold_rate: 0.5

  # beta: 0.001
  epsilon: 0.02

  # init_lr: 0.00005
  # min_lr: 0.00001
  decay_steps: 50
  decay_rate: 0.7
