build_path: 
  win32: C:\Users\Fisher\Documents\Unity\build-simple-roller\rl-test.exe
  linux: /data/linux-simple-roller/rl-test.x86_64
write_summary_graph: true
seed_increment: 100
decay_steps: 70
decay_rate: 0.7
critic:
  init_td_threshold: 0.01
  td_threshold_decay_steps: 100
  decay_steps: 70
  decay_rate: 0.7