build_path: 
  win32: C:\Users\Fisher\Documents\Unity\build-test-boat\boat.exe
  linux: /data/zzy/linux-test-boat/boat.x86_64
write_summary_graph: true
seed_increment: 1
decay_steps: 500
decay_rate: 0.8
max_iter: 10000
lambda: 0.95