build_path: 
  win32: C:\Users\Fisher\Documents\Unity\build-test-boat\boat.exe
  linux: /data/zzy/linux-test-boat/boat.x86_64
write_summary_graph: true

max_iter: 1000
use_auto_alpha: True
use_priority: True
batch_size: 256
replay_buffer_capacity: 1000000